spring.application.name=notification-service
#to not collide with core-api port
server.port=8081

#Variables
app.company.email=jwarys.carrentalapi@gmail.com

#RabitMQ configuration
spring.rabbitmq.port = 5672
spring.rabbitmq.host = localhost
spring.rabbitmq.listener.simple.retry.enabled = true
spring.rabbitmq.listener.simple.retry.max-attempts = 5
spring.rabbitmq.listener.simple.retry.initial-interval = 1000ms

#Mailhog configuration
spring.mail.host = localhost
spring.mail.port = 1025
spring.mail.properties.mail.smtp.auth=false
