spring.application.name=notification-service
#to not collide with core-api port
server.port=8081

#RabitMQ configuration
spring.rabitmq.port = 5672
spring.rabitmq.host = localhost

#Mailhog configuration
spring.mail.host = localhost
spring.mail.port = 1025
spring.mail.properties.mail.smtp.auth=false
