spring.application.name=car-rental-api

spring.datasource.url=jdbc:postgresql://localhost:5432/car_rental_db
spring.datasource.username=postgres
spring.datasource.password=testPassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:jkrzERduXiDX3CzfQL08FdL1oAr4PbwBMy6GrQAY4VG}

app.company.email=rental@rental.com