name: CI Pipeline for Car Rental system

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run the Maven verify phase in core-api
        working-directory: ./core-api
        run: ./mvnw clean verify
